### PR TITLE
Update LoginService.java

### PR DESCRIPTION
**Pull request by Jenishrz**
Hi Boss,
Can you please review my code and let me know the necessary updates.
Thank You.

### CODE REVIEW

**Review by DharshuAlagar23 — APPROVED** [review]
Hi Jenish,
Yes, I have reviewed your LoginService.java file, In that you have failed to give return response message.Can you please add it.
Thank you.

**Comment by Jenishrz** [comment]
> Hi Jenish, Yes, I have reviewed your LoginService.java file, In that you have failed to give return response message.Can you please add it. Thank you.

Hi Boss,
I have updated my code which changes has changes you have given. Now I will merge the pull request.
Thank you.

**Comment by DharshuAlagar23** [comment]
> > Hi Jenish, Yes, I have reviewed your LoginService.java file, In that you have failed to give return response message.Can you please add it. Thank you.
> 
> Hi Boss, I have updated my code which changes has changes you have given. Now I will merge the pull request. Thank you.

Hi Jenish,
Yes, Now you code is fine.You can merge it and close pull request.
Thank you

**Comment by Jenishrz** [comment]
Hi Boss,
Yes, I have merged and closed the pull request.
Thank you.

**Pull request merged**
